export const FACTORY_ABI = [
  {
    inputs: [],
    name: 'getGroupsCount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'index', type: 'uint256' }],
    name: 'getGroupAddressByIndex',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getGroupAddresses',
    outputs: [{ internalType: 'address[]', name: '', type: 'address[]'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getPlatformWallet',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getCapacityUpgradeCost',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [
        { internalType: 'string', name: 'title', type: 'string' },
        { internalType: 'string', name: 'telegramGroupUrl', type: 'string' },
        { internalType: 'string', name: 'coordinatorTelegramUsername', type: 'string' },
        { internalType: 'uint256', name: 'coordinatorCommissionPercentage', type: 'uint256' },
        { internalType: 'uint256', name: 'contributionAmountInWei', type: 'uint256' },
        { internalType: 'uint256', name: 'prizePercentage', type: 'uint256' },
    ],
    name: 'createGroup',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getGroupSettings',
    outputs: [
      {
        components: [
          { internalType: 'string', name: 'title', type: 'string' },
          { internalType: 'string', name: 'telegramGroupUrl', type: 'string' },
          {
            components: [
              { internalType: 'address', name: 'memberAddress', type: 'address' },
              { internalType: 'string', name: 'telegramUsername', type: 'string' },
              { internalType: 'bool', name: 'isCoordinator', type: 'bool' },
              { internalType: 'bool', name: 'isActiveVoter', type: 'bool' },
            ],
            internalType: 'struct ExternalMember',
            name: 'coordinator',
            type: 'tuple',
          },
          { internalType: 'uint256', name: 'coordinatorCommissionPercentage', type: 'uint256' },
          { internalType: 'uint256', name: 'contributionAmountInWei', type: 'uint256' },
          { internalType: 'uint256', name: 'prizePercentage', type: 'uint256' },
          { internalType: 'uint256', name: 'maxCapacity', type: 'uint256' },
          { internalType: 'uint256', name: 'capacityUpgradeCount', type: 'uint256' },
          { internalType: 'bool', name: 'openJoinEnabled', type: 'bool' },
        ],
        internalType: 'struct GroupSettings',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getMembersCount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getActiveVotersCount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'memberAddress', type: 'address' }],
    name: 'getMemberByAddress',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'memberAddress', type: 'address' },
          { internalType: 'string', name: 'telegramUsername', type: 'string' },
          { internalType: 'bool', name: 'isCoordinator', type: 'bool' },
          { internalType: 'bool', name: 'isActiveVoter', type: 'bool' },
        ],
        internalType: 'struct ExternalMember',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'person', type: 'address' }],
    name: 'isMember',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getPeriodsCount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const;
